### ISSUE TITLE
ScrollView not working with gestures

### ISSUE THREAD

**Issue by JohBa** [softlion/XamarinFormsGesture#10]
It seems like there are several problems with swipe gestures in a ScrollView.
On UWP I've got the problem, that swipe gestures aren't working anyway but scrolling does.
On Android (tested on Nexus 5X) scrolling isn't working anymore but swipe gestures seem to work.
iOS unfortunately currently not testable for me.

You can find a sample project in https://github.com/JohBa/XFIntro/tree/master/XFIntro/XFIntro concerned files are called `ScrollViewWithSwipe`.

Let me know if I can help to fix, I would like to!
Completely working, this feature would be awesome.

**Update** ok, sorry my bad. It surely works when I move the gesture to the stacklayout, but it is really hard to hit the swipe gesture and not trigger the scrollview. Is there anything we can do about it?!

**Comment by rusty02** [comment]
@JohBa I'm having the same issue when using a webview that i need to scroll down or up. Were you able to find a solution to this issue?

**Comment by softlion** [comment]
See #12, same issue.
