### ISSUE TITLE
Swipe gesture not working on webview

### ISSUE THREAD

**Issue by yeonsann** [softlion/XamarinFormsGesture#11]
Hello

I noticed that when you use the  left or right swipe gestures on a webview, I'm unable to scroll the webview down or up. 
I hope you can fix this as soon as possible

Thanks in advace

**Comment by softlion** [comment]
Hi, there is no support for multiple gesture recognizers in forms. Until then there is no solution. You may fix it and pull request in xamarin forms to improve this behavior.
