### ISSUE TITLE
Tap gestures not working in iOS release builds

### ISSUE THREAD

**Issue by valentinba** [softlion/XamarinFormsGesture#14]
I recently ran into an issue where the routing effect which installs the gesture recognizers was not properly resolved in iOS release builds (I only tried on iOS 12, with the build running on MacOS Mojave/XCode 10, using the latest Visual Studio 2017 for Windows and VS for Mac).

The core issue may be an over eager iOS build optimization which strips out the call to Init, resulting in the iOS assembly not being loaded and the effect failing to resolve silently.

I described the issue in more details and a possible workaround here https://github.com/xamarin/Xamarin.Forms/issues/3910. 

Hope this helps.

**Comment by softlion** [comment]
iOS Linker has always been very aggressive.
Just preserve the constructor of the effect by calling it in an unused method marked with the [Preserve] attribute.

**Comment by valentinba** [comment]
Shouldn't the workaround be mentioned in the documentation in case someone else runs into this issue?

**Comment by softlion** [comment]
It is already written in the Xamarin documentation. It's the same problem for every components stored in the ioc.

**Comment by softlion** [comment]
https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/linker?tabs=vsmac

**Comment by softlion** [comment]
You are right, there are things to do.

**Comment by softlion** [comment]
fixed
