### ISSUE TITLE
Pinch gesture doesn't work

### ISSUE THREAD

**Issue by dthaler** [softlion/XamarinFormsGesture#15]
There's no pinch gesture in this project, and using gestures in this project breaks the Xamarin.Forms pinch gesture.   This issue was reported in https://stackoverflow.com/questions/52419986/when-i-add-tap-gesture-the-pinch-and-pan-does-not-work-in-xamarin-forms

It was suggested in
https://forums.xamarin.com/discussion/17767/touch-coordinates-in-tapgesturerecognizer
that this might be fixable in Android by adding 
```
touchEventArgs.Handled = false;
```
to ControlOnTouch() in XamarinFormsGesture.Droid\PlatformGestureEffect.cs

**Comment by softlion** [comment]
Could you try and create a pull request ?

**Comment by softlion** [comment]
Fixed

**Comment by dthaler** [comment]
Where was this fixed?  I'm not finding a recent commit.
