### ISSUE TITLE
link tapcommand2 to image pixel

### ISSUE THREAD

**Issue by pdeman** [softlion/XamarinFormsGesture#17]
Hi,
I linked the tapCommand2 to an image in the xaml.
`<Image Source="{local:ImageResource Project.MyImage}" Aspect="AspectFill" " ui:Gesture.TapCommand2="{Binding test}"></Image>`

I get the tapped position and now i am trying to get from it which image pixel it's corresponding to.
any idea how to do that?

**Comment by raymondjstone** [comment]
Might be worth explaining why you need  to know where in the image you are, since you are using aspect fill and presuming you are using a variety of platforms and screen sizes surely  your image will not be a fixed dimension and so the exact position may not be what you want if you are using pixels based on your source image size

**Comment by pdeman** [comment]
i am trying to get the pixel location of some features that i identify
visually and tap on it.

and ideally i want to draw an object over the image to show where i tapped. but define by the pixel location for it to be well positionned if visualized with another device later.

Le jeu. 14 mars 2019 à 19:14, Raymond Stone <notifications@github.com> a
écrit :

**Comment by pdeman** [comment]
and ideally i want to draw an object over the image to show where i tapped.
but define by the pixel location for it to be well positionned if
visualized with another device later.

deman pierre
+33 7 82 57 80 94

**Comment by raymondjstone** [comment]
At a rough guess

- Check what args in the eventargs construct for the gesture you have trapped
- if not including location on screen then you may need to use the pan gesture to get get it or write a custom gesture recogniser 
- find the position of start corner and dimensions of your image as rendered
- using basic maths you can then translate the current offset to an offset within your image and by applying the ratio between original and rendered you can determine what you need

**Comment by pdeman** [comment]
> 
>     * find the position of start corner and dimensions of your image as rendered
> 
>     * using basic maths you can then translate the current offset to an offset within your image and by applying the ratio between original and rendered you can determine what you need

ok thanks, I was wondering if there was already some methods to do that instead of doing that by myself.

**Comment by softlion** [comment]
Now it is called TapPointCommand, and the command is Command<Point> where point is the point location. To convert it into a pixel position you must multiply by the UIKit Scale factor for iOS, and the equivalent for Android.
