### ISSUE TITLE
iOS: unable to parse ui:Guesture 

### ISSUE THREAD

**Issue by sistla001** [softlion/XamarinFormsGesture#2]
`Xamarin.Forms.Xaml.XamlParseException: Position 11:88. Type Gesture not found in xmlns clr-namespace:Vapolia.Lib.Ui;assembly=XamarinFormsGesture`

```
<Image Source="https://s3-us-west-1.amazonaws.com/powr/defaults/image-slider2.jpg" ui:Gesture.TapCommand2="{Binding ImageTappedCommand}"></Image>
```
No issues on Droid. 

Can you please look into it? Thanks

**Comment by hungbqit** [comment]
Same issue... please help. Thanks

**Comment by mmierzwa** [comment]
Same here. I guess this package shared the fate of many once-released-never-maintained libs...

**Comment by softlion** [comment]
Works perfectly there. Sorry no time to debug your projects.
