### ISSUE TITLE
PanCommand raise unhandled error at Android

### ISSUE THREAD

**Issue by ivoryguard** [softlion/XamarinFormsGesture#20]
Hello.

I found an issue of Pan gesture command.

I set PanCommand to a BoxView like this;
```xml
<BoxView BackgroundColor="#0C000000" gesture:Gesture.PanCommand="{Binding PanSideToolbarHandlerCommand}" InputTransparent="False"/>
```
When I run my app and perform pan gesture at Android device, the following error occurred;

`
Unhandled Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Android.Util.DisplayMetrics'. occurred
`

I tried to debug XamarinFormsGesture by downloading Github full source and compiling. However, All gesture defined in GitHub Demo app did not work at Android device though there were not compile error except I changed Target Framework to Android 8.0 to Android 9.0. I confirmed PlatformGestureEffect was called but OnFling method was not called never, tough I did not change your source code.

My environment -
Windows 10 Pro
Visual Studio 2019
XamarinFormsGeture version – 3.0.1
Target Framework – Android 9.0
Device OS – Android 5.0.1 and 6.0

Best regards.

**Comment by softlion** [comment]
Ok fixed in vnext.
