### ISSUE TITLE
Library not recognized in the UWP project.

### ISSUE THREAD

**Issue by Informatheus** [softlion/XamarinFormsGesture#24]
The library for the Init() command was recognized in the Android and iOS project, but in the UWP it does not.

![image](https://user-images.githubusercontent.com/3857461/85109353-9561d580-b1e7-11ea-8609-15507d9f4a92.png)

**Comment by softlion** [comment]
![image](https://user-images.githubusercontent.com/190756/85114742-c0195180-b21a-11ea-84e3-bc3b92af359a.png)

**Comment by Informatheus** [comment]
Sorry, i tried both ways but only sent uwp.
![image](https://user-images.githubusercontent.com/3857461/85153655-d3351d00-b22c-11ea-9915-f7953669d660.png)

**Comment by softlion** [comment]
UWP requires fall creator update
