### ISSUE TITLE
How to pass CommandParameter?

### ISSUE THREAD

**Issue by Informatheus** [softlion/XamarinFormsGesture#25]
I really need to pass the object in question or its position in the listview as a parameter to Command. How do I do this?

**Comment by softlion** [comment]
You code it :) Look at source code its easy.

**Comment by Informatheus** [comment]
Sorry, I looked at the project, I looked at the demo, and I didn't find how to do that. The library has only the types of gestures and their commands, but there is nothing about parameters.
![image](https://user-images.githubusercontent.com/3857461/85155057-a6820500-b22e-11ea-9a71-651d9a68636b.png)

**Comment by softlion** [comment]
Yes there is no parameter, feel free to code it and PR ! :)
