### ISSUE TITLE
Crash if use this inside of controltemplate

### ISSUE THREAD

**Issue by Alex-Dobrynin** [softlion/XamarinFormsGesture#28]
if i use tap command inside of controltemplate and trying to change controltemplates dynamically I get crash on android. and i had to switch back to gexture recognizers

![image](https://user-images.githubusercontent.com/23138430/96854052-bff8bf00-1463-11eb-8e45-a51fcaaf20df.png)

![image](https://user-images.githubusercontent.com/23138430/96854166-e3bc0500-1463-11eb-967e-688317cc5dbd.png)

**Comment by softlion** [comment]
can you post a repro project ? Or modify the existing demo project to repo this crash ? I don't see any XamarinFormsGesture call in this stack trace.

**Comment by Alex-Dobrynin** [comment]
![image](https://user-images.githubusercontent.com/23138430/101770952-e47f2800-3af1-11eb-998a-4017c8a5b6ce.png)
what is this? this is commented XamarinFormsGesture which crash the application if it is not commented
just comment gesture recognizers and uncomment ui:Gesture.TapCommand

this control template is used for ContentView, you can use this one and switch dynamically (in runtime, triggered by some event or button click or whatever) to another controltemplate you want and get crash described above. also you may not use SvgCachedImage (it is just code from my project) and you can set static height and width (it does not matter).

Also, if you don`t know how controltemplating works, go to the official xamarin forms documentation.

Also, I`ve noticed that if i use XamarinFormsGesture from DataTemplate, I also get crash when I tap on item, this gesture is attached to. And in this case crash log is the same

**Comment by softlion** [comment]
I can't see this nuget in the stack trace you posted.

**Comment by Alex-Dobrynin** [comment]
Yeah, but this command uses control renderers to get onTouch events on android, doesn't it? Also you can try to reproduce this bug
