### ISSUE TITLE
Pinch Gesture Not Working on Android

### ISSUE THREAD

**Issue by yonkahlon** [softlion/XamarinFormsGesture#31]
Firstly, thanks so much for an awesome library!

I'm not getting any pinch events when running the demo app.

I did some digging, and it looks like the issue is in the Android PlatformGestureEffect:

```
public override bool OnDown(MotionEvent? e)
{
    if (e!=null && IsPanImmediate && e.PointerCount == 1 && PanAction != null)
        return PanAction.Invoke(e, e);

    if (e != null && IsPinchImmediate && e.PointerCount == 2 && PinchAction != null)
    {
        PinchAction?.Invoke(e, e);
        return true;
    }

    return false;
}
```

e.PointerCount is always 1. It doesn't fire again when my second finger touches the screen. Then when you move your 2 fingers, it enters the following method in the same file:
```
public override bool OnScroll(MotionEvent? initialDown, MotionEvent? currentMove, float distanceX, float distanceY)
{
    if (initialDown != null)
    {
        if(initialDown.PointerCount == 1 && PanAction != null)
            return PanAction.Invoke(initialDown, currentMove);

        if (initialDown.PointerCount == 2 && PinchAction != null)
        {
            PinchAction.Invoke(initialDown, currentMove);
            return true;
        }
    }
    return false;
}
```

In this case initialDown.PointerCounter is always 1 (CurrentMove.PointerCounter is 2 though), so it never fires the PinchAction event.

I don't know much about Android gestures, I'm more familiar with iOS, so I couldn't quite work out how to fix that. The easy solution is to not include the initialDown point in the event or to somehow detect the first time the OnScroll method is called with 2 pointersm and then use that as the initialDown point. Neither of these feel like the right solution but that's how I'm going to try working around it for now.

Would love to get your input on this :-). Should OnDown be called twice and essentially convert a pan gesture into a pinch gesture?

**Comment by yonkahlon** [comment]
Just as a reference, here is my workaround:

```
private MotionEvent? _pinchInitialDown;
public void OnUp(MotionEvent? e)
{
    if(e != null)
        PanAction?.Invoke(e, e);

    _pinchInitialDown = null;
}

public override bool OnScroll(MotionEvent? initialDown, MotionEvent? currentMove, float distanceX, float distanceY)
{
    if (currentMove != null && initialDown != null)
    {
        if (_pinchInitialDown == null && initialDown.PointerCount == 1 && currentMove.PointerCount == 2)
        {
            _pinchInitialDown = MotionEvent.Obtain(currentMove);
        }

        if(currentMove.PointerCount == 1 && PanAction != null)
            return PanAction.Invoke(initialDown, currentMove);

        if (currentMove.PointerCount == 2 && PinchAction != null && _pinchInitialDown != null)
        {
            PinchAction.Invoke(_pinchInitialDown, currentMove);
            return true;
        }
    }
    return false;
}
```

**Comment by softlion** [comment]
Ty @yonkahlon  ! It's in next rc.
