### ISSUE TITLE
Long tap on ListView doesn't work when there is a Gesture attached to it.

### ISSUE THREAD

**Issue by Mikelly** [softlion/XamarinFormsGesture#6]
Hello, 

appreciate the effort, your gestures work very nicely.

But I have one issue, when using your gestures (swipe) on ListView, that ListView stops recognizing long tap that should popup context menu on listItem. Single taps are working, and also swipes work OK. When I remove your gestures long tap starts working again.

Is there anything I can do to make this work, or am I doing something wrong way?

**Comment by softlion** [comment]
On some platforms you can modify the behavior so the gesturerecognizer can recognize gesture simultaneously with another control. you'll need to update this code though.
