### ISSUE TITLE
Issue Installing in Xamarin form .NETPortable 4.5

### ISSUE THREAD

**Issue by RizalAnshori** [softlion/XamarinFormsGesture#9]
Hello, your plugin is great and very usefull, but when i change my xamarin framework to 4.5, i can't interate it anymore, is there some update or clue to fix it?? o.O thank for your good reply

![image](https://user-images.githubusercontent.com/19476831/38479522-f45fbf3c-3be9-11e8-915b-914a49aa7972.png)

**Comment by softlion** [comment]
Change your project's profile to netstandard.
